// src/components/widgets/SideToolBar/TocButton.vue
<script setup lang="ts">
import { t } from '@utils/i18n';
import { onMounted, onUnmounted, ref } from 'vue';

const isOpen = ref(false);
const isWideScreen = ref(false);
const hasToc = ref(false);
const tocWrapper = ref<HTMLElement | null>(null);

const handleResize = () => {
  if (window.innerWidth > 1280) {
    isWideScreen.value = true;
  } else {
    isWideScreen.value = false;
  }
};

onMounted(() => {
  const setup = () => {
    const toc = document.getElementById('toc');
    if (toc && tocWrapper.value) {
      hasToc.value = true;
      const remainAttrs = ['class', 'style'];
      tocWrapper.value.innerHTML = '';
      tocWrapper.value.appendChild(toc.cloneNode(true));
      tocWrapper.value.children[0].id = 'stb-toc-content';
      Array.from(tocWrapper.value.children[0].attributes).forEach((attr) => {
        if (!remainAttrs.includes(attr.name)) {
          tocWrapper.value!.children[0].removeAttribute(attr.name);
        }
      });
    }
    window.addEventListener('resize', handleResize);
    handleResize();
  };
  const cleanup = () => {
    isOpen.value = false;
    if (tocWrapper.value) tocWrapper.value.innerHTML = '';
    hasToc.value = false;
    window.removeEventListener('resize', handleResize);
    isWideScreen.value = false;
  };

  document.addEventListener('astro:page-load', setup);
  setup();
  document.addEventListener('astro:before-swap', cleanup);
});

onUnmounted(() => {
  if (tocWrapper.value) tocWrapper.value.innerHTML = '';
  hasToc.value = false;
  window.removeEventListener('resize', handleResize);
  isWideScreen.value = false;
});
</script>

<template>
  <div
    :class="{
      hidden: !hasToc || isWideScreen,
    }"
  >
    <button
      ref="buttonRef"
      class="btn btn-circle btn-secondary btn-sm"
      @click="isOpen = !isOpen"
      :title="t.info.toc()"
      :aria-label="t.info.toc()"
      :aria-expanded="isOpen"
      :aria-controls="'stb-toc-wrapper'"
    >
      <slot name="icon" />
    </button>
    <div
      ref="tocWrapper"
      id="stb-toc-wrapper"
      class="rounded-box absolute w-[calc(100vw-4rem)] -translate-x-1/2 -translate-y-1/2 max-w-72 backdrop-blur-md duration-300 text-base-content text-start"
      :inert="!isOpen || isWideScreen"
      :class="{
        '-translate-x-[calc(100%+0.5rem)]! -translate-y-[calc(100%-2.5rem)]!':
          isOpen && !isWideScreen,
        'scale-0 opacity-0': !isOpen || isWideScreen,
      }"
    />
  </div>
</template>

// src/components/widgets/SideToolBar/TocButton.tsx
import { t } from '@utils/i18n';
import type { ParentComponent } from 'solid-js';
import { createSignal, onCleanup, onMount } from 'solid-js';

const TocButton: ParentComponent = (props) => {
  const [isOpen, setIsOpen] = createSignal(false);
  const [isWideScreen, setIsWideScreen] = createSignal(false);
  const [hasToc, setHasToc] = createSignal(false);
  let tocWrapperRef: HTMLDivElement | undefined;
  let buttonRef: HTMLButtonElement | undefined;

  const handleResize = () => {
    setIsWideScreen(window.innerWidth > 1280);
  };

  const setup = () => {
    const toc = document.getElementById('toc');
    const wrapper = tocWrapperRef;
    if (toc && wrapper) {
      wrapper.innerHTML = '';
      wrapper.appendChild(toc.cloneNode(true));
      (wrapper.children[0] as HTMLElement).id = 'stb-toc-content';

      const remainAttrs = ['class', 'style'];
      Array.from((wrapper.children[0] as Element).attributes).forEach((attr) => {
        if (!remainAttrs.includes(attr.name)) {
          (wrapper.children[0] as Element).removeAttribute(attr.name);
        }
      });

      setHasToc(true);
    } else {
      setHasToc(false);
    }

    window.addEventListener('resize', handleResize);
    handleResize(); // 初始一次
  };

  const cleanup = () => {
    setIsOpen(false);
    setHasToc(false);
    tocWrapperRef!.innerHTML = '';
    window.removeEventListener('resize', handleResize);
    setIsWideScreen(false);
  };

  onMount(() => {
    document.addEventListener('astro:page-load', setup);
    setup();
    document.addEventListener('astro:before-swap', cleanup);

    onCleanup(() => {
      document.removeEventListener('astro:page-load', setup);
      document.removeEventListener('astro:before-swap', cleanup);
      cleanup();
      setIsOpen(false);
      tocWrapperRef!.innerHTML = '';
    });
  });

  return (
    <div
      classList={{
        hidden: !hasToc() || isWideScreen(),
      }}
    >
      <button
        ref={buttonRef}
        type="button"
        class="btn btn-circle btn-secondary btn-sm"
        title={t.info.toc()}
        aria-label={t.info.toc()}
        aria-expanded={isOpen()}
        aria-controls="stb-toc-wrapper"
        onClick={() => setIsOpen((v) => !v)}
      >
        {props.children}
      </button>

      <div
        ref={tocWrapperRef}
        id="stb-toc-wrapper"
        classList={{
          'rounded-box absolute w-[calc(100vw-4rem)] -translate-x-1/2 -translate-y-1/2 max-w-72 backdrop-blur-md duration-300 text-base-content text-start': true,
          'scale-0 opacity-0': !isOpen() || isWideScreen(), // closed
          '-translate-x-[calc(100%+0.5rem)]! -translate-y-[calc(100%-2.5rem)]!':
            isOpen() && !isWideScreen(),
          hidden: !hasToc() || isWideScreen(),
        }}
        inert={!isOpen() || isWideScreen()}
      />
    </div>
  );
};

export default TocButton;
